version: "2"
services:
  influxdb:
    image: influxdb:0.12
    volumes:
      - ./influxdb/data:/var/lib/influxdb
      - ./influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
    ports:
      - "8083:8083"
      - "8086:8086"
      - "2003:2003"

  grafana:
    image: grafana/grafana:3.0.1
    environment:
      - INFLUXDB_NAME=gatling
      - INFLUXDB_HOST=influxdb
    volumes:
      - ./grafana/run.sh:/run.sh:ro
      - ./grafana/data:/var/lib/grafana
    ports:
      - "3000:3000"
    links:
      - influxdb
